CREATE TABLE IF NOT EXISTS `#__downloadtracker_products` (
	`id` int NOT NULL AUTO_INCREMENT,
	`title` varchar(255) NOT NULL,
	`alias` varchar(255) NOT NULL,
	`description` text NULL,
	`state` tinyint NOT NULL DEFAULT 1,
	`created` datetime NULL,
	`created_by` int unsigned NOT NULL DEFAULT 0,
	`modified` datetime NULL,
	`modified_by` int unsigned NOT NULL DEFAULT 0,
	`ordering` int NOT NULL DEFAULT 0,
	`checked_out` int unsigned NULL,
	`checked_out_time` datetime NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_alias` (`alias`),
	KEY `idx_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__downloadtracker_items` (
	`id` int NOT NULL AUTO_INCREMENT,
	`product_id` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`alias` varchar(255) NOT NULL,
	`edition` varchar(50) NULL,
	`version` varchar(50) NULL,
	`source_type` varchar(20) NOT NULL DEFAULT 'external',
	`target_url` text NOT NULL,
	`private_file` varchar(1024) NULL,
	`requires_token` tinyint NOT NULL DEFAULT 0,
	`customer_instructions` text NULL,
	`update_enabled` tinyint NOT NULL DEFAULT 0,
	`update_element` varchar(255) NULL,
	`update_type` varchar(20) NULL,
	`update_folder` varchar(100) NULL,
	`update_client` varchar(20) NOT NULL DEFAULT 'site',
	`update_sha256` char(64) NULL,
	`update_targetplatform` varchar(100) NULL,
	`update_php_minimum` varchar(20) NULL,
	`is_latest` tinyint NOT NULL DEFAULT 0,
	`state` tinyint NOT NULL DEFAULT 1,
	`notes` text NULL,
	`created` datetime NULL,
	`created_by` int unsigned NOT NULL DEFAULT 0,
	`modified` datetime NULL,
	`modified_by` int unsigned NOT NULL DEFAULT 0,
	`ordering` int NOT NULL DEFAULT 0,
	`checked_out` int unsigned NULL,
	`checked_out_time` datetime NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_alias` (`alias`),
	KEY `idx_product_id` (`product_id`),
	KEY `idx_state` (`state`),
	KEY `idx_latest` (`is_latest`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__downloadtracker_tokens` (
	`id` bigint NOT NULL AUTO_INCREMENT,
	`item_id` int NOT NULL,
	`label` varchar(255) NULL,
	`token_hash` char(64) NOT NULL,
	`token_prefix` varchar(16) NULL,
	`purpose` varchar(20) NOT NULL DEFAULT 'download',
	`state` tinyint NOT NULL DEFAULT 1,
	`expires_at` datetime NULL,
	`max_uses` int unsigned NULL,
	`used_count` int unsigned NOT NULL DEFAULT 0,
	`customer_email` varchar(320) NULL,
	`note` text NULL,
	`last_used_at` datetime NULL,
	`emailed_at` datetime NULL,
	`emailed_to` varchar(320) NULL,
	`email_count` int unsigned NOT NULL DEFAULT 0,
	`last_email_status` varchar(50) NULL,
	`last_email_error` text NULL,
	`source` varchar(50) NULL,
	`source_reference` varchar(255) NULL,
	`created` datetime NULL,
	`created_by` int unsigned NOT NULL DEFAULT 0,
	`modified` datetime NULL,
	`modified_by` int unsigned NOT NULL DEFAULT 0,
	`checked_out` int unsigned NULL,
	`checked_out_time` datetime NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `idx_token_hash` (`token_hash`),
	KEY `idx_item_id` (`item_id`),
	KEY `idx_purpose` (`purpose`),
	KEY `idx_state` (`state`),
	KEY `idx_expires_at` (`expires_at`),
	KEY `idx_source_reference` (`source`, `source_reference`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__downloadtracker_logs` (
	`id` bigint NOT NULL AUTO_INCREMENT,
	`item_id` int NOT NULL,
	`product_id` int NOT NULL,
	`downloaded_at` datetime NOT NULL,
	`requested_alias` varchar(255) NULL,
	`edition` varchar(50) NULL,
	`version` varchar(50) NULL,
	`resolved_version` varchar(50) NULL,
	`ip_address` varchar(45) NULL,
	`user_agent` text NULL,
	`is_bot` tinyint NOT NULL DEFAULT 0,
	`bot_reason` varchar(100) NULL,
	`referrer` text NULL,
	`requested_url` text NULL,
	`target_url` text NOT NULL,
	`token_id` bigint NULL,
	`token_prefix` varchar(16) NULL,
	`token_status` varchar(30) NULL,
	`status` varchar(20) NOT NULL DEFAULT 'redirected',
	`ip_classification` varchar(50) NULL,
	`country_code` varchar(10) NULL,
	`country_name` varchar(100) NULL,
	`continent_code` varchar(10) NULL,
	`continent_name` varchar(100) NULL,
	`asn` varchar(50) NULL,
	`asn_name` varchar(255) NULL,
	`asn_domain` varchar(255) NULL,
	`ip_location_provider` varchar(100) NULL,
	`ip_location_checked_at` datetime NULL,
	`ip_location_status` varchar(50) NULL,
	`ip_location_response` mediumtext NULL,
	PRIMARY KEY (`id`),
	KEY `idx_item_id` (`item_id`),
	KEY `idx_product_id` (`product_id`),
	KEY `idx_downloaded_at` (`downloaded_at`),
	KEY `idx_is_bot` (`is_bot`),
	KEY `idx_status` (`status`),
	KEY `idx_token_id` (`token_id`),
	KEY `idx_token_status` (`token_status`),
	KEY `idx_ip_location_checked_at` (`ip_location_checked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
